version: "3.8"

services:
  api:
    container_name: go-commerce
    image: golang:1.23-alpine
    build: .
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      - db

  db:
    container_name: go-commerce-db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: go-commerce-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
